// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC_Inquiry
{
    static readonly InquiryClass s_Inquiry = new InquiryClass();
    public static InquiryClass Inquiry { get { return s_Inquiry; } }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class InquiryClass
    {
        public readonly string Name = "Inquiry";
        public DcmsMobile.Inquiry.Areas.Inquiry.BoxEntity.BoxEntityController BoxEntity = new DcmsMobile.Inquiry.Areas.Inquiry.BoxEntity.T4MVC_BoxEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.CartonAreaEntity.CartonAreaEntityController CartonAreaEntity = new DcmsMobile.Inquiry.Areas.Inquiry.CartonAreaEntity.T4MVC_CartonAreaEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.CartonEntity.CartonEntityController CartonEntity = new DcmsMobile.Inquiry.Areas.Inquiry.CartonEntity.T4MVC_CartonEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.CustomerEntity.CustomerEntityController CustomerEntity = new DcmsMobile.Inquiry.Areas.Inquiry.CustomerEntity.T4MVC_CustomerEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.Home.HomeController Home = new DcmsMobile.Inquiry.Areas.Inquiry.Home.T4MVC_HomeController();
        public DcmsMobile.Inquiry.Areas.Inquiry.IntransitEntity.IntransitEntityController IntransitEntity = new DcmsMobile.Inquiry.Areas.Inquiry.IntransitEntity.T4MVC_IntransitEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.PickslipEntity.PickslipEntityController PickslipEntity = new DcmsMobile.Inquiry.Areas.Inquiry.PickslipEntity.T4MVC_PickslipEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.ReturnEntity.ReturnEntityController ReturnEntity = new DcmsMobile.Inquiry.Areas.Inquiry.ReturnEntity.T4MVC_ReturnEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.ShipmentEntity.ShipmentEntityController ShipmentEntity = new DcmsMobile.Inquiry.Areas.Inquiry.ShipmentEntity.T4MVC_ShipmentEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.SkuAreaEntity.SkuAreaEntityController SkuAreaEntity = new DcmsMobile.Inquiry.Areas.Inquiry.SkuAreaEntity.T4MVC_SkuAreaEntityController();
        public DcmsMobile.Inquiry.Areas.Inquiry.SkuEntity.SkuEntityController SkuEntity = new DcmsMobile.Inquiry.Areas.Inquiry.SkuEntity.T4MVC_SkuEntityController();
        public T4MVC.Inquiry.SharedViewsController SharedViews = new T4MVC.Inquiry.SharedViewsController();
    }
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_PartialViewResult : System.Web.Mvc.PartialViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_PartialViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links_Inquiry
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string jquery_2_1_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.1.min.js") ? Url("jquery-2.1.1.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/jquery-2.1.1.min.js") : Url("jquery-2.1.1.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/jquery-2.1.1.js");
                public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/jquery.validate.min.js") : Url("jquery.validate.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/jquery.validate.js");
                public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/jquery.validate.unobtrusive.js");
                }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Areas {
        private const string URLPATH = "~/Areas";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Inquiry {
            private const string URLPATH = "~/Areas/Inquiry";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class BoxEntity {
                private const string URLPATH = "~/Areas/Inquiry/BoxEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class CartonAreaEntity {
                private const string URLPATH = "~/Areas/Inquiry/CartonAreaEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class CartonEntity {
                private const string URLPATH = "~/Areas/Inquiry/CartonEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Carton_png = Url("Carton.png")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/Carton.png");
                public static readonly string Pallet_jpg = Url("Pallet.jpg")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/Pallet.jpg");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class CustomerEntity {
                private const string URLPATH = "~/Areas/Inquiry/CustomerEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Home {
                private const string URLPATH = "~/Areas/Inquiry/Home";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string bootstrap3_typeahead_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap3-typeahead.min.js") ? Url("bootstrap3-typeahead.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/bootstrap3-typeahead.min.js") : Url("bootstrap3-typeahead.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/bootstrap3-typeahead.js");
                        }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class IntransitEntity {
                private const string URLPATH = "~/Areas/Inquiry/IntransitEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string IntransitShipmentList_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/IntransitShipmentList.min.css") ? Url("IntransitShipmentList.min.css")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/IntransitShipmentList.min.css") : Url("IntransitShipmentList.css")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/IntransitShipmentList.css");
                     
                public static readonly string IntransitShipmentList_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/IntransitShipmentList.min.js") ? Url("IntransitShipmentList.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/IntransitShipmentList.min.js") : Url("IntransitShipmentList.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/IntransitShipmentList.js");
                        }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class PickslipEntity {
                private const string URLPATH = "~/Areas/Inquiry/PickslipEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ReturnEntity {
                private const string URLPATH = "~/Areas/Inquiry/ReturnEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class SharedViews {
                private const string URLPATH = "~/Areas/Inquiry/SharedViews";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string responsivegroup_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/responsivegroup.min.js") ? Url("responsivegroup.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/responsivegroup.min.js") : Url("responsivegroup.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/responsivegroup.js");
                        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/Site.min.css") : Url("Site.css")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/Site.css");
                     
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class ShipmentEntity {
                private const string URLPATH = "~/Areas/Inquiry/ShipmentEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class SkuAreaEntity {
                private const string URLPATH = "~/Areas/Inquiry/SkuAreaEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string SkuLocation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/SkuLocation.min.js") ? Url("SkuLocation.min.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/SkuLocation.min.js") : Url("SkuLocation.js")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/SkuLocation.js");
                        }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class SkuEntity {
                private const string URLPATH = "~/Areas/Inquiry/SkuEntity";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            public static readonly string Web_config = Url("Web.config")+"?"+T4MVCHelpers.TimestampString(URLPATH + "/Web.config");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009


